export const FETCH_REPO_DATA_PENDING = 'FETCH_REPO_DATA_PENDING'
export const FETCH_REPO_DATA_REJECTED = 'FETCH_REPO_DATA_REJECTED'
export const FETCH_REPO_DATA_FULFILLED = 'FETCH_REPO_DATA_FULFILLED'
